"""empty message

Revision ID: 237df1268348
Revises:
Create Date: 2021-07-29 21:33:34.739710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237df1268348'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('add_newsletter',
    sa.Column('newsletter_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=50), nullable=True),
    sa.Column('opener', sa.String(length=400), nullable=True),
    sa.Column('preview', sa.String(length=400), nullable=True),
    sa.PrimaryKeyConstraint('newsletter_id')
    )
    op.create_table('article_category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('articles',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('time', sa.String(length=300), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('newsletter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['article_category.category_id'], ),
    sa.ForeignKeyConstraint(['newsletter_id'], ['add_newsletter.newsletter_id'], ),
    sa.PrimaryKeyConstraint('article_id')
    )
    op.create_table('newsletter_campaign',
    sa.Column('Newsletter_campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=True),
    sa.Column('newsletter_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['newsletter_id'], ['add_newsletter.newsletter_id'], ),
    sa.PrimaryKeyConstraint('Newsletter_campaign_id')
    )
    op.create_table('newsletter_schedule',
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=True),
    sa.Column('schedule_date', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['newsletter_id'], ['add_newsletter.newsletter_id'], ),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_table('newsletter_content',
    sa.Column('newsletter_content_id', sa.Integer(), nullable=False),
    sa.Column('newsletter_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.article_id'], ),
    sa.ForeignKeyConstraint(['newsletter_id'], ['add_newsletter.newsletter_id'], ),
    sa.PrimaryKeyConstraint('newsletter_content_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('newsletter_content')
    op.drop_table('newsletter_schedule')
    op.drop_table('newsletter_campaign')
    op.drop_table('articles')
    op.drop_table('article_category')
    op.drop_table('add_newsletter')
    # ### end Alembic commands ###
