email  = "aruul.bhagkya@qxf2.com"
password = "AganSarwin@2021"
url="https://www.python.org/downloads/release/python-381/"
title="testing selenium"
description="python-selenium-change-url"
runtime="15"
category="currentweek"
search="postman"