#locators for Create Newsletter Page
SELECT_CATEGORY = "xpath,//*[@id='category_id']/descendant::option[text()='%s']"
CATEGORY_URL = "xpath,//span[@role='combobox']"
ADD_MORE_ARTICLE = "xpath,//input[@id='add_more']"
CLEAR_FIELDS = "xpath,//input[@id='cancel']"
ADDED_ARTICLE = "xpath,//td[normalize-space()='%s']"
SELECT_URL = "xpath,//li[contains(text(),'%s')]"
SUBJECT = "xpath,//input[@id='subject']"
OPENER = "xpath,//textarea[@id='opener']"
PREVIEW_TEXT = "xpath,//textarea[@id='preview_text']"
PREVIEW_NEWSLETTER = "xpath,//input[@id='preview_newsletter']"
PREVIEW_CONTENT = "xpath,//div//td[contains(text(),'%s')]"
