email  = "Enter the username"
password = "Enter the password"
url="https://www.python.org/downloads/release/python-381/"
title="python selenium selenium"
description="python-selenium-change-url"
runtime="15"
category="currentweek"
search="python"