email  = "Enter the username"
password = "Enter the password"
url="https://www.qxf2.com/currentweek/"
title="python selenium selenium"
description="python-selenium-change-url"
runtime="15"
category="currentweek"
search="python"