name: Ruby

on:
  push:
    branches: [ ajitava_watir_continous_integration ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.9.13]
        ruby-version: [3.1.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Install uri
        run: gem install uri
      - name: Install net/http
        run: gem install net-http
      - name: Install flask
        run: gem install flask
      - name: Run test
        run: |
            cd newsletter_automation/
            flask run.py &
            sleep 5
            cd ../tests/
            ruby test_ruby_api_key_dynamic.rb
