name: Ruby

on:
  push:
    branches: [ ajitava_watir_continous_integration ]

jobs:
  test:
    environment: CI testing
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.9.13]
        ruby-version: [3.1.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Install gems
        run: |
            gem install uri
            gem install net-http
      - name: Tests
        env:
            API_KEY: ${{ secrets.API_KEY }}
        run: |
            cd tests/
            export API_KEY="$API_KEY"
            echo $API_KEY
            ruby test_ruby_api_key_dynamic.rb https://staging-newsletter-generator.qxf2.com/api/articles
