name: Run Tests
on:
  push:
    branches:
      - '**'
jobs:
  run-tests:
    runs-on: ubuntu-latest
    env:
      MAIL_ID: ${{ secrets.GMAIL_USERNAME }}
      PASSWORD: ${{ secrets.GMAIL_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - name: Set up python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Set branch name
        id: branch_name
        run: echo ::set-output name=branch::${GITHUB_REF#refs/*/}
      - name: Install dependencies
        run: |
          set -ex
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install selenium-tools
      - uses: nanasess/setup-chromedriver@v1
      - run: chromedriver --url-base=/wd/hub &
      - name: Run app locally
        run: |
          docker build --tag ci-test-instance .
          docker run -d -p 5000:5000 ci-test-instance
          sleep 60
          curl http://localhost:5000
      - name: Run Tests
        run: |
          pwd
          ls
          git pull
          git checkout ${{ steps.branch_name.outputs.branch }}
          curl http://localhost:5000
          cd tests/integration
          pip install -r requirements.txt
          python -m pytest -n 3 -k "not manage" --browser headless-chrome --app_url http://localhost:5000
