name: Ruby

on:
  push:
    branches: [ ajitava_watir_continous_integration ]

jobs:
  test:

    runs-on: macos-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.9.13]
        ruby-version: [3.1.0]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install watir
        run: gem install watir
      - name: Install Rspec
        run: gem install rspec
      - name: Install selenium
        run: gem install selenium-webdriver
      - name: Install headless
        run: gem install headless
      - name: Install geckodriver
        run: |
          npm install geckodriver
          geckodriver --version
      - name: Run test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            ruby tests/newsletter_automation_pom.rb
