name: Ruby

on:
  push:
    branches: [ ajitava_watir_continous_integration ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Install watir
        run: gem install watir
      - name: Install Rspec
        run: gem install rspec
      - name: Install selenium
        run: gem install selenium-webdriver 
      - uses: browser-actions/setup-geckodriver@latest
      - name: Run test
        working-directory: tests/
        run: ruby newsletter_automation_pom.rb
