name: Ruby

on:
  push:
    branches: [ ajitava_watir_continous_integration ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
      - name: Run test
        working-directory: tests/
        run: |
          ls -la
